vector_store:
  type: "milvus"
  host: "localhost"
  port: 19530
  collection_name: "documents"

embedding_model:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  device: "cuda"

document_processor:
  chunk_size: 512
  chunk_overlap: 50
  supported_formats: ["pdf", "txt", "docx"]

llm:
  provider: "openai"  # or "anthropic", "huggingface"
  model_name: "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 500

rag:
  retriever:
    search_type: "mmr"  # or "similarity"
    k: 4  # number of documents to retrieve
    fetch_k: 20  # number of documents to fetch before filtering
    lambda_mult: 0.5  # diversity factor for MMR
  
  chain:
    type: "stuff"  # or "map_reduce", "refine", "map_rerank"
    verbose: true

monitoring:
  log_level: "INFO"
  metrics_port: 8000

mlflow:
  tracking_uri: "http://localhost:3500"
  experiment_name: "rag-document-processing"

minio:
  endpoint: "localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket_name: "documents"
  secure: false