vector_store:
  type: "milvus"
  host: "localhost"
  port: 19530
  collection_name: "documents"

embedding_model:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  device: "cuda"

document_processor:
  chunk_size: 512
  chunk_overlap: 50
  supported_formats: ["pdf", "txt", "docx"]

monitoring:
  log_level: "INFO"
  metrics_port: 8000

mlflow:
  tracking_uri: "http://localhost:3500"
  experiment_name: "rag-document-processing"

minio:
  endpoint: "localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket_name: "documents"
  secure: false